import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service — WINi",
  description: "Terms governing your use of the WINi wine pairing service.",
};

export default function TermsPage() {
  return (
    <main
      className="min-h-screen px-6 py-16 max-w-2xl mx-auto"
      style={{ background: "var(--charcoal)", color: "var(--cream-lightest)" }}
    >
      <Link
        href="/"
        className="inline-block mb-8 text-sm"
        style={{ fontFamily: "var(--font-jost-family)", color: "var(--gold)", textDecoration: "underline", textUnderlineOffset: "3px" }}
      >
        &larr; Back to WINi
      </Link>

      <h1
        className="text-3xl mb-8"
        style={{ fontFamily: "var(--font-cormorant-family)", fontWeight: 700 }}
      >
        Terms of Service
      </h1>

      <div className="space-y-6 text-sm leading-relaxed" style={{ fontFamily: "var(--font-jost-family)", color: "rgba(250, 246, 240, 0.8)" }}>
        <p><strong style={{ color: "var(--cream-lightest)" }}>Effective date:</strong> March 2026</p>

        <Section title="1. The Service">
          <p>
            WINi (&ldquo;Wine Intelligence&rdquo;) is an AI-powered wine pairing assistant.
            You upload menu photos or describe dishes, and WINi suggests wine pairings.
            The service is provided by Alfred Leppanen (&ldquo;we&rdquo;, &ldquo;us&rdquo;).
          </p>
        </Section>

        <Section title="2. Eligibility">
          <p>
            You must be at least 18 years old to use WINi. By creating an account,
            you confirm you meet the legal drinking age in your jurisdiction.
          </p>
        </Section>

        <Section title="3. Your Account">
          <ul className="list-disc pl-5 space-y-1">
            <li>You are responsible for keeping your login credentials secure.</li>
            <li>You may delete your account at any time from Account settings.</li>
            <li>We may suspend accounts that violate these terms.</li>
          </ul>
        </Section>

        <Section title="4. Acceptable Use">
          <p>You agree not to:</p>
          <ul className="list-disc pl-5 space-y-1 mt-1">
            <li>Upload illegal, harmful, or offensive content.</li>
            <li>Attempt to reverse-engineer, scrape, or overload the service.</li>
            <li>Use automated tools to mass-access the API.</li>
            <li>Impersonate others or misrepresent your identity.</li>
          </ul>
        </Section>

        <Section title="5. AI-Generated Content">
          <p>
            Wine pairing recommendations are generated by AI and are for informational
            purposes only. WINi does not guarantee accuracy of tasting notes, food pairing
            suggestions, or wine availability. Always consult a sommelier or wine professional
            for important occasions.
          </p>
        </Section>

        <Section title="6. Intellectual Property">
          <p>
            The WINi name, logo, and design are our intellectual property.
            Content you upload (menu photos) remains yours. AI-generated pairing
            results are provided for your personal use.
          </p>
        </Section>

        <Section title="7. Payment & Subscriptions">
          <p>
            Premium features may require a paid subscription via Stripe.
            Subscriptions auto-renew unless cancelled. Refunds are handled per
            Stripe&apos;s policies.
          </p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>
            WINi is provided &ldquo;as is&rdquo; without warranties. We are not liable for
            decisions made based on AI recommendations, including but not limited to
            wine purchases, allergic reactions, or unsatisfactory dining experiences.
          </p>
        </Section>

        <Section title="9. Changes to Terms">
          <p>
            We may update these terms. Continued use after changes constitutes acceptance.
            Material changes will be communicated via email or in-app notification.
          </p>
        </Section>

        <Section title="10. Governing Law">
          <p>
            These terms are governed by Finnish law. Disputes will be resolved in
            Finnish courts.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions about these terms? Email:{" "}
            <a href="mailto:legal@alfredleppanen.com" style={{ color: "var(--gold)" }}>
              legal@alfredleppanen.com
            </a>
          </p>
        </Section>
      </div>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-lg mb-2" style={{ fontFamily: "var(--font-cormorant-family)", fontWeight: 600, color: "var(--cream-lightest)" }}>
        {title}
      </h2>
      {children}
    </section>
  );
}
